import type { Metadata } from "next";
import "@hypercore/ui/styles/globals.css";
import localFont from "next/font/local";

const switzer = localFont({
  src: "./fonts/Switzer-Variable.ttf",
  variable: "--font-switzer",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={switzer.className}>{children}</body>
    </html>
  );
}
